### ISSUE TITLE
Missing to catch errors properly

### ISSUE THREAD

**Issue by mariolamacchia** [PugliaSOS/howsweather#5]
.howsweather file:
```
{
  "city": "Mountain View",
  "api_key": "daefffed335bdf68b726fee93bb7ba61"
}
```

Result:
```
$ howsweather

howsweather | visualize weather, from console
Retrieving weather for 'MOUNTAIN VIEW'..
/usr/local/lib/node_modules/howsweather/src/openweatherapi.js:30
        let weatherStatus = data.weather[0].main;
                                        ^

TypeError: Cannot read property '0' of undefined
    at IncomingMessage.parseWeather (/usr/local/lib/node_modules/howsweather/src/openweatherapi.js:30:41)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by mariolamacchia** [comment]
It works now, probably it was a connection issue. Shouldn't it show a readable error if something goes wrong?

**Comment by ghost** [comment]
Yeah, I miss to catch it.
